### ISSUE TITLE
please collect follow-up contact info

### ISSUE THREAD

**Issue by brahn** [lizthegrey/signbot#15]
Hey Liz -- first, thanks so much for doing this!  We had a great time at Stripe yesterday tabling and helping folks sign up (esp. non-engineers for whom the github process is far too intimidating) but this will make organizing much much easier. (And we'll keep tabling anyway! It'll just go faster.)

Now the feedback :-)  Please forgive me if this is obvious/redundant/already discussed, I can only see what's on the site.

I think it's really important to collect email addresses so you can follow-up with signatories about what's happening, follow-on actions, etc.  The pledge is a great starting point for building a community of tech folks who want to take further action. I would be really sad if this opportunity fell through the crack.

On quick scan of [process.go](https://github.com/lizthegrey/signbot/blob/master/backend/src/signprocessor/process.go) it seems like this is all stateless other than creating the PR, but I might be missing something!  Assuming that's right, though -- there's no current mechanism to store contents other than the public repo, and I imagine many people would not want their email in there, so there'd need some sort of private backend (db, private github repo, even just logging where one could extract later).

Please let me know if this direction would be welcome, etc. Happy to help however I can.

**Comment by lizthegrey** [comment]
As far as discussing follow-on actions and how to contact signatories: please file an issue against https://github.com/neveragaindottech/neveragaindottech.github.io so the wider organizers can see it.

As far as the second point goes: yes, we'd like to eventually make some of the information private (e.g. handling pulls in private repo and squashing finished commits stripped of evaluation info to the public repo) so that volunteers only rather than the whole world have access to information when evaluating pull requests. That would enable us to feel better about transiently storing slightly more identifying information. [but we'd obviously need to update the privacy policy too.

**Comment by lizthegrey** [comment]
It turns out github does not allow creating a private fork of a public repo so this is less feasible than I imagined :(

**Comment by brahn** [comment]
Oh github :-(  

But!  Standing up a proper db should be doable.  Or, perhaps using something like mailchimp to store the email addresses and get full email campaign functionality (with unsubscribe, etc.)  Will continue over in https://github.com/neveragaindottech/neveragaindottech.github.io/issues/1856

**Comment by brahn** [comment]
(and thanks for investigating!)
